server:
  port: ${port:8080}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${APPLICATION_DB_URL}
    username: ${APPLICATION_DB_USERNAME}
    password: ${APPLICATION_DB_PASSWORD}
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
cloud:
  aws:
    credentials:
      accessKey: ${APPLICATION_ACCESSKEY}
      secretKey: ${APPLICATION_SECRETKEY}
    s3:
      bucket: ${APPLICATION_BUCKET}
    region:
      static: ap-northeast-2
jwt:
  secret: ${APPLICATION_JWT}